### ISSUE TITLE
Check PlayReady version on Windows 10

### ISSUE THREAD

**Issue by Jason239** [MicrosoftDocs/PlayReady#105]
Is there a way to check whether the PlayReady Client version used by players in the Edge browser is 3.x or 4.x?

**Comment by sergiofagostinho** [comment]
@Jason239 AFAIK, not exactly (something which would be interesting), but it is it possible to determine which features are supported, using [edge://media-internals/](edge://media-internals/) and selecting the "CDMs" tab. You should get something like this:
```
com.microsoft.playready
PlayReady Content Decryption Module
software-secure
0.0.0.1
C:\Program Files (x86)\Microsoft\Edge\Application\96.0.1054.62\PlayReadyCdm\_platform_specific\win_x64\playreadycdm.dll
{"Audio Codecs":[],"Encryption Schemes":["CENC"],"Session Types":["temporary","persistent-license"],"Video Codecs":{"av1":[],"dolbyvision":[],"h264":[],"hevc":[],"vp8":[],"vp9":[]}}
```
So, in my case (version `96.0.1054.62` of Edge running on `Microsoft Windows [Version 10.0.18363.1916]`) it seems to be <= **4.0**, as according the [Product Versions](https://docs.microsoft.com/en-us/playready/overview/product-versions) page, cbcs on software was added in 4.2, and it's missing here.

**Comment by Jason239** [comment]
Thanks for your reply !
I think that information is really useful.

However, now CBCS encrypted content can be played(with license using PR Server SDK 4.4) on my Edge browser, but that information represents `Encryption Schemes":["CENC"]`.
So this is a little bit hard to understand..

> Windows now supports CBCS for both hardware and software DRM. Additionally, the PlayReady license server extends CBCS support for SL2000.

I also saw these comments in the [MS docs page](https://docs.microsoft.com/en-us/playready/overview/what-is-new/what-is-new-4-4)

The page may not have been updated I think.

**Comment by Jason239** [comment]
Ah, so does this information maybe represent only hardware information?
It would make sense if the cbcs content was played on software DRM.

**Comment by sergiofagostinho** [comment]
Hi @Jason239 , unfortunately, it's hard to get accurate information regarding CBCS support.

I've seen a training video from Microsoft where it's mentioned in the Q&A that all supported Windows 10 versions (in March 2021) support CBCS in software mode (SL2000), but not all hardware implementations (SL3000) support it. @swenkeratmicrosoft 's comment on https://github.com/MicrosoftDocs/PlayReady/issues/70 seems to be consistent with this statement.

However, it's not clear for me if Windows 10 support for CBCS _implies_ Edge support for CBCS. Based on my brief testing within my team, I have yet to find any Windows 10 machine that claims CBCS on Edge, at least via the media internals page.

**Comment by swenkeratmicrosoft** [comment]
You cannot check the PK version directly, but you can check for the specific feature you require (which is better).

In Edge, the best way to check for CBCS support is using the following API.

MSMediaKeys.isTypeSupportedWithFeatures

It uses the same query format as the following API.
https://docs.microsoft.com/en-us/uwp/api/windows.media.protection.protectioncapabilities.istypesupported?view=winrt-22000

As mentioned, this should only be used on Windows 10, version 1607 or newer OS version.  Of course, 1607 (Redstone 1) is so old that it's been out support since mid-2019, so the customer base on builds that old is pretty small.

For the key system string, you should always use com.microsoft.playready.recommendation.3000 for HWDRM and com.microsoft.playready.recommendation for SWDRM.  Do NOT use "com.microsoft.playready.hardware" - the documentation for that API is out of date (and I've been working to get it updated).

Note that you will NOT get accurate data for 'cbcs' unless you also specify ALL of the following as well.
1. MIME type   (because some codecs may support 'cbcs' while others may not, on the same machine)
2. decode-res-x and decode-res-y  (because some codecs may only support 'cbcs' at certain resolutions)

I don't know enough about the media internals page itself to comment on its information, but the above API will correctly provide client support in Edge, the OS, and (if applicable) the hardware.

Last remark: The server must also support CBCS for the end-to-end scenario to work.

Hope that helps,

-Sam Wenker with the Microsoft PlayReady team

**Comment by Jason239** [comment]
Thanks for your answer.
It really helped me a lot :)
