### ISSUE TITLE
Secure Stop on Windows Edge browser

### ISSUE THREAD

**Issue by Jason239** [MicrosoftDocs/PlayReady#109]
Hi,

There's something I want to check for sure.

https://docs.microsoft.com/en-us/playready/features/secure-stop-pk#secure-stop-2

According to this page, when implementing Secure Stop Service, we can only receive Secure Stop Data from SL3000 environment. 
So, is it correct that Secure Stop service is not available to web player in Windows Edge browser?

**Comment by astravaganza** [comment]
edge can also use SL3000

**Comment by swenkeratmicrosoft** [comment]
The current EME specification has entirely cut support for the persistent-usage-record session type which is required for Secure Stop.

https://www.w3.org/TR/encrypted-media/#dom-mediakeysessiontype

As a result, because Chromium has also removed support for it, the entire Secure Stop feature is no longer supported in Edge.
