### ISSUE TITLE
What about PR 4.1 and 4.2?

### ISSUE THREAD

**Issue by jmwhite5** [MicrosoftDocs/PlayReady#57]
This page seems outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 585dbb37-8920-731b-bd8b-32586290688a
* Version Independent ID: 963485d8-e61d-a415-741e-04457bdf5202
* Content: [PlayReady Product Versions - PlayReady](https://docs.microsoft.com/en-us/playready/overview/product-versions#feedback)
* Content Source: [Docs/Overview/product-versions.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Overview/product-versions.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
Thank you for your feedback!  If you believe the following resolution is incomplete, feel free to reactivate this issue with additional details.

The page has been updated with versions 4.2, 4.3, and 4.4.  Since there was no public release for PlayReady 4.1, that version is not included.

-Sam Wenker with the Microsoft PlayReady team
