### ISSUE TITLE
How to know Playready client version on Win 10 PC (for cbcs support)

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/PlayReady#70]
I am using Edge 80.0.361.111 on Win 10.0.18363 Enterprise to playback CMAF content encrypted in cbcs scheme but I run into the following exception when a license is requested:
```
System.Web.Services.Protocols.SoapException: Internal service error
   at Microsoft.Media.Drm.RightsManager.ConvertRmServerException(RMServerException ex)
   at Microsoft.Media.Drm.RightsManager.AcquireLicense(XmlDocument challenge)
```
The request body in 
[req.txt](https://github.com/MicrosoftDocs/PlayReady/files/4486503/req.txt)
indicates the client version as
							<CLIENTVERSION>10.0.16384.10011</CLIENTVERSION>

How do I know if Playready on my Win 10 PC supports cbcs? The documentation mentions only Xbox One 1709 or higher but https://www.microsoft.com/playready/newsroom/ announces it for 2018:

> Support for AES-CBC content encryption - Microsoft adds support for AES-CBC keys to PlayReady 4.0. A PlayReady Server SDK and a PlayReady Client Porting Kit version 4.0 is being released in September 2017 to allow services and OEMs to add this new feature to their devices and device applications. AES-CBC will be rolling out on Windows clients starting with Xbox One, Xbox S, Xbox X before holiday 2017 for use of HLS and DASH. Windows 10 PCs will receive an update later in 2018 that brings AES-CBC decoding to new devices that have AES-CBC capable hardware.

How can I confirm that cbcs is indeed not yet supported on Win 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af2d299-d877-2ec4-8173-15572fe0c2f0
* Version Independent ID: 188849b2-32fc-30ab-ce75-1c2ede2c17c7
* Content: [PlayReady Content Encryption Modes - PlayReady](https://docs.microsoft.com/en-us/playready/packaging/content-encryption-modes#feedback)
* Content Source: [Docs/Packaging/content-encryption-modes.md](https://github.com/MicrosoftDocs/PlayReady/blob/live/Docs/Packaging/content-encryption-modes.md)
* Product: **playready**
* Technology: **drm**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by swenkeratmicrosoft** [comment]
'cbcs' support depends on more than simply your Windows 10 OS version.  It can also depend on things like your hardware, your drivers, etc.

Fortunately, you can query for support within the browser itself on the client.

In all recent versions of Chromium-Edge (which is what you indicated you are using), you can check for 'cbcs' support using the "encryptionScheme" string in the MediaKeySystemMediaCapability passed to requestMediaKeySystemAccess.

Additional details can be found here:

https://github.com/WICG/encrypted-media-encryption-scheme/blob/master/explainer.md

Note that 'cbcs' support can also be affected by other things in the requestMediaKeySystemAccess query.  For example, your hardware or drivers might support 'cbcs' for some codecs and not others, it might be supported in Software DRM but not Hardware DRM (or vice-versa), etc.  In other words, you should always specify all relevant information related to the content you want to play when calling requestMediaKeySystemAccess.

Querying within the browser should always give you accurate information in Chromium-Edge, so that's what I would recommend.

Regarding the PlayReady Server SDK:

It is *possible* to determine that the PlayReady portion of the client supports 'cbcs' before issuing a license, but only if your PlayReady Server SDK is version 4.4 or higher.  For more information, refer to the "How to Determine What Features a Client Supports" topic.

Even with that said:
1. The server SDK won't tell you anything about codec/driver support, for example.  It is PlayReady-specific information.
2. Even then, the Server SDK has three possible values for support.
-) Definitely supported (LicenseChallenge.ReeFeatureList is populated and includes LicenseChallengeReeFeatures.AESCBCS)
-) Definitely not supported (LicenseChallenge.ReeFeatureList is populated and does NOT include LicenseChallengeReeFeatures.AESCBCS)
-) Unknown (LicenseChallenge.ReeFeatureList is not populated).

The third case will be very common on Windows 10.  Very few graphics cards and very few OS builds are built on PlayReady 4.4 or higher, and previous versions do not pass this information to the server.

Hope that helps,

-Sam Wenker with the Microsoft PlayReady team

**Comment by Murmur** [comment]
@swenkeratmicrosoft  I have a `TestEME cenc,cbcs,cbcs-1-9` function but Win10-Edge-Playready always give `cbsc=false` flags. Widevine and Clearkey gives `cbcs=true` flags. Edge(dashjs) player however playbacks  all three `Playready+Widevine+Clearkey` cbcs test content fine.

See this simple javascript page:
https://m.dtv.fi/dash/dashjs/index.html
